source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APUContactPicker_Example', :exclusive => true do
  pod "APUContactPicker", :path => "../"
end

target 'APUContactPicker_Tests', :exclusive => true do
  pod "APUContactPicker", :path => "../"

  
end
